title: deeboo experiments
description: deeboo experiments and notes for development

url: http://rolimat.github.io/deeboo
baseurl: "deeboo"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 #- title: Contact
  # url: /contact

social:
   github: rolimat
   twitter: empollica
   #facebook: brianmaierjr
   email: rolimat@gmail.com

google_analytics: "UA-63699864-1"
