title: deeboo experiments
description: deeboo experiments and notes for development

url: http://rolimat.github.io
baseurl: "/deeboo"
paginate_path: "blog/page:num/"
permalink: :title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Links
   url: /links.html
 - title: About
   url: /about.html

social:
   github: rolimat
   twitter: empollica
   #facebook: brianmaierjr
   email: rolimat@gmail.com

google_analytics: "UA-63699864-1"
